# Generated by Django 3.1.7 on 2021-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlab', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phno',
            field=models.CharField(max_length=12),
        ),
    ]
