# Generated by Django 3.1.7 on 2021-06-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlab', '0007_auto_20210626_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodsugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdate', models.DateField()),
                ('observedval', models.IntegerField()),
                ('fasting', models.BooleanField(default=0)),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
