# Generated by Django 3.1.7 on 2021-07-08 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlab', '0008_bloodsugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='cholesterol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdate', models.DateField()),
                ('totalcholesterol', models.IntegerField()),
                ('ldl', models.IntegerField()),
                ('hdl', models.IntegerField()),
                ('triglycerides', models.IntegerField()),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
