# Generated by Django 3.1.7 on 2021-07-14 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlab', '0009_cholesterol'),
    ]

    operations = [
        migrations.CreateModel(
            name='urinalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdate', models.DateField()),
                ('color', models.TextField()),
                ('turpidity', models.TextField()),
                ('ph', models.IntegerField()),
                ('glucose', models.TextField()),
                ('bilirubin', models.TextField()),
                ('blood', models.TextField()),
                ('protien', models.TextField()),
                ('leukocyte', models.TextField()),
                ('userid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
